### ISSUE TITLE
Account is getting locked

### ISSUE THREAD

**Issue by rouge-creator** [qqvm/Facebook-Events-iOS#1]
My FB account got locked while trying to fetch all the birthdays. Is there a way to fix this issue from happening again and again?

**Comment by qqvm** [comment]
Did you get any errors?
Did loading indicator appear too frequently?

**Comment by rouge-creator** [comment]
Ya this seems to be the case. I was fetching the data too much and the data was not being cached since I added a few more fields to fetch. So I am assuming that if someone were to just fetch once, this issue won't occur at all?

**Comment by rouge-creator** [comment]
The loading indicator did appear frequently. One time I logged the full list of birthdays, and during that time, the loading indicator was on for 30 seconds plus. Could that have been the cause?

**Comment by qqvm** [comment]
If you fetch same _doc_id_ from graphql too frequently, Facebook may limit such requests. In some cases they could even ban the account.
